namespace: frr-k8s-system

resources:
- ../../default

patches:
- path: frr-k8s_testenv_patch.yaml
  target:
    kind: DaemonSet
    name: frr-k8s-daemon
  options:
    allowNameChange: false
- path: statuscleaner_testenv_patch.yaml
  target:
    kind: Deployment
    name: statuscleaner
  options:
    allowNameChange: false
