apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: frr-k8s-daemon
  namespace: frr-k8s-system
spec:
  template:
    spec:
      containers:
      - name: controller
        args:
        - "--metrics-bind-address=127.0.0.1:7572"
        - "--node-name=$(NODE_NAME)"
        - "--namespace=$(NAMESPACE)"
        - "--log-level=debug"
        - "--pod-name=$(POD_NAME)"
        - "--always-block=192.167.9.0/24,fc00:f553:ccd:e799::/64"
      - name: frr-status
        args:
        - "--node-name=$(NODE_NAME)"
        - "--namespace=$(NAMESPACE)"
        - "--pod-name=$(POD_NAME)"
        - "--poll-interval=5s" 
